/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MoodAnalyser;

public class MoodAnalyser {
	String message;
	public MoodAnalyser(String message) {
		this.message=message;
	}
	
    public String analyseMood(String message) {
        if(message.contains("sad"))
        	return "SAD";
        else
        	return "HAPPY";
                
    }
    
    public String analyseMood() throws MoodAnalysisException {
    	try {
    		if(message.contains("sad"))
    			return "SAD";
    		else
    			return "HAPPY";
    	}catch(NullPointerException e) {
    		throw new MoodAnalysisException("Please enter proper message");
    	}
                
    }
}
