/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MoodAnalyser;

import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.junit.Assert.*;

import org.hamcrest.CoreMatchers;
import org.junit.Assert;

public class MoodAnalyserTest {
    @Test public void analyseMood_SadMessage_SAD() throws Exception {
        MoodAnalyser moodAnalyser = new MoodAnalyser("This is a sad message");
        
        String mood=moodAnalyser.analyseMood();
        Assert.assertThat(mood, CoreMatchers.is("SAD"));
    }
    @Test public void analyseMood_NotASadMessage_HAPPY() throws Exception {
        MoodAnalyser moodAnalyser = new MoodAnalyser("I am in any mood");
        
        String mood=moodAnalyser.analyseMood();
        Assert.assertThat(mood, CoreMatchers.is("HAPPY"));
    }
    
    @Test public void analyseMood_givenNullMood_HAPPY() {
    	MoodAnalyser moodAnalyser = new MoodAnalyser(null);
        
        String mood;
		try {
			ExpectedException exceptionRule=ExpectedException.none();
			exceptionRule.expect(MoodAnalysisException.class);
			mood = moodAnalyser.analyseMood();
			Assert.assertEquals("HAPPY",mood);
		} catch (MoodAnalysisException e) {
			e.printStackTrace();
		}
       
    	
    }
    
}
