/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MoodAnalyser;

import org.junit.Test;
import static org.junit.Assert.*;

import org.hamcrest.CoreMatchers;
import org.junit.Assert;

public class MoodAnalyserTest {
    @Test public void analyseMood_SadMessage_SAD() throws Exception {
        MoodAnalyser moodAnalyser = new MoodAnalyser();
        
        String mood=moodAnalyser.analyseMood("This is a sad message");
        Assert.assertThat(mood, CoreMatchers.is("SAD"));
    }
    @Test public void analyseMood_SadMessage_HAPPY() throws Exception {
        MoodAnalyser moodAnalyser = new MoodAnalyser();
        
        String mood=moodAnalyser.analyseMood("This is a happy message");
        Assert.assertThat(mood, CoreMatchers.is("HAPPY"));
    }
    
    @Test public void analyseMood_givenNullMood_HAPPY() {
    	MoodAnalyser moodAnalyser = new MoodAnalyser();
        
        String mood=moodAnalyser.analyseMood(null);
        Assert.assertEquals("HAPPY",mood);
    	
    }
    
}
